### ISSUE TITLE
Type of BSD license, explicit license file

### ISSUE THREAD

**Issue by pmlandwehr** [sbrunner/sphinx-prompt#17]
Hey-lo,

I'm building a version of `sphinx-prompt` using [`conda`](http://conda.pydata.org/) for [conda-forge](http://conda-forge.github.io/). When possible, we try to include a link to the license file in the `meta.yaml` specification for the build; doing so requires the license be indexed in an explicit [`MANIFEST.in`](https://docs.python.org/2/distutils/sourcedist.html#manifest-related-options) file so that it gets included in the source distribution. Also, in the case of BSD licenses, it means that we need to know whether the package is licensed under the [BSD 2-Clause](https://opensource.org/licenses/BSD-2-Clause) or [BSD 3-Clause](https://opensource.org/licenses/BSD-3-Clause) variant.

Would you consider specifying which kind of BSD license you're using, adding a license file to the repo, and including it in the build via `MANIFEST.in`? Thanks very much!

**Comment by gtback** [comment]
@sbrunner, I'd be happy to make these changes. I personally use the 3-clause BSD more than 2-clause, but don't really have a stake in the outcome. 

Let me know if I can help.

**Comment by sbrunner** [comment]
+1 :-)
