### ISSUE TITLE
sphinx-prompt fails pip installs when using requirements files in a virtual environment

### ISSUE THREAD

**Issue by barbaricyawps** [sbrunner/sphinx-prompt#174]
I work in a documentation development environment where we generate and preview our Sphinx documentation in a virtual environment using the Python `venv` module. The way our venv works is that we list `sphinx-prompt` as an extension in our Sphinx `conf.py` file. For example:

```
extensions = [
    "sphinx-prompt", # Required by sphinx_substitution_extensions
    "sphinx_substitution_extensions",
]
```

Lately, `sphinx-prompt` has been failing to download when generating our Sphinx files. The workaround is to do a direct pip install of the `sphinx-prompt` package in your environment, but that's not an ideal long-term solution. We'd like it to work the way it used to work where it could download the package from PyPi the way it should work with Sphinx.

Any ideas on how to fix it?

**Comment by barbaricyawps** [comment]
Actually, I misspoke: the workaround is to add it to a `requirements.txt` file for the virtual environment. But I still don't know why it fails to download as part of the Sphinx extension process.

**Comment by sbrunner** [comment]
Is it steel valid?
