### ISSUE TITLE
Indented lines in prompt

### ISSUE THREAD

**Issue by domdfcoding** [sbrunner/sphinx-prompt#25]
Hi,

I'm trying to use sphinx-prompt with code that has indents, such as this:

```rest
.. prompt:: python >>>,... auto

    >>> for i in range(10):
    ...     print(i)
```

I would expect the tab on the `print(i)` line to be included in the output, but it isn't. 

I can see that on line 109 `.strip()` gets called on the line, which removes whitespace at the start and end of the line, including my indentation.

If I change `.strip()` to `.rstrip()` the indents get included in the output.

Is this the intended behaviour?

Thanks 😀

**Comment by sbrunner** [comment]
Yes, you're right, can you provide a pull request?
