### ISSUE TITLE
Consider removing upperbound on the Python version

### ISSUE THREAD

**Issue by Jackenmen** [sbrunner/sphinx-prompt#369]
It is not recommended to have upper bounds on the Python version in Python packages. Currently, this means that this package cannot be installed on Python 3.11.

Some resources on this:
https://iscinumpy.dev/post/bound-version-constraints/
https://discuss.python.org/t/requires-python-upper-limits/12663

**Comment by sbrunner** [comment]
In #370 I increase the upper bounds, I will investigate later on how to completely remove it...
