### ISSUE TITLE
Add Windows's Batch (cmd) and PowerShell languages

### ISSUE THREAD

**Issue by jack1142** [sbrunner/sphinx-prompt#64]
It would be great to get Batch and PowerShell languages (`BatchLexer` and `PowerShellLexer`) and their prompts (`>` or sth like `C:\>` for cmd and `PS>` or sth like `PS C:\>` for PowerShell).

I can try making a PR if you're interested.

**Comment by sbrunner** [comment]
Yes, you're welcome :-)
