### ISSUE TITLE
Is there any way to have a prompt with a space?

### ISSUE THREAD

**Issue by jack1142** [sbrunner/sphinx-prompt#65]
I was wondering if it's in any way possible to have a prompt with a space, for example:
```
(some-venv) $ python -m pip install -U ...
```

**Comment by jack1142** [comment]
It seems that this is a limitation of positional arguments in directives, this could be solved using options, e.g:
```rst
.. prompt::
    :prompts: (some-venv) $

     python -m pip install -U ...
```

For convenience and backwards-compatibility, the positional arguments could be retained but the options would be preferred if provided.

What do you think?

**Comment by sbrunner** [comment]
> For convenience and backwards-compatibility, the positional arguments could be retained but the options would be preferred if provided.

Yes, and raise a warning if possible :-)
